In [39]:
import pandas as pd
import numpy as np

In [44]:
names = ['Lenght','Group Size','Percentage Increase','Employee Contribution Base','Status']
df = pd.read_csv('./CSV/random_data.csv')
df.set_index('Member ID')

,Length,Group Size,Percentage Increase,Employee Contribution Base,Status
Member ID,,,,,
2,55,26,0.04,8,Active
3,92,86,0.03,1,Active
4,63,58,0.04,3,Active
5,45,109,0.04,5,Active
6,117,63,0.05,4,Active
7,119,72,0.03,1,Active
8,5,52,0.05,2,Termed
9,102,42,0.05,10,Active
10,11,16,0.05,2,Termed
11,9,32,0.03,5,Termed
12,6,51,0.05,9,Termed
13,152,48,0.05,6,Active
14,77,32,0.05,1,Active
15,87,89,0.05,7,Active
16,11,1,0.05,5,Termed
17,94,108,0.05,10,Active
18,34,104,0.04,7,Active
19,25,52,0.05,5,Active
20,2,10,0.03,2,Termed
21,12,61,0.03,10,Termed
22,11,108,0.03,5,Termed
23,138,65,0.04,2,Active
24,7,98,0.04,7,Termed
25,3,44,0.05,1,Termed
26,77,33,0.04,3,Active
27,3,108,0.04,10,Termed
28,1,9,0.04,6,Termed
29,1,35,0.03,5,Termed
30,2,106,0.04,1,Termed
31,12,103,0.04,10,Termed
...,...,...,...,...,...
29971,103,3,0.03,10,Active
29972,143,98,0.03,8,Active
29973,88,57,0.03,2,Active
29974,62,19,0.05,1,Active
29975,150,57,0.03,1,Active
29976,3,65,0.03,1,Termed
29977,85,19,0.04,5,Active
29978,10,33,0.04,10,Termed
29979,75,81,0.05,4,Active
29980,7,67,0.04,1,Termed
29981,3,25,0.05,3,Termed
29982,10,3,0.04,5,Termed
29983,5,94,0.04,1,Termed
29984,51,63,0.04,5,Active
29985,107,57,0.03,6,Active
29986,79,16,0.04,9,Active
29987,6,34,0.03,2,Termed
29988,8,91,0.05,10,Termed
29989,2,25,0.03,10,Termed
29990,10,109,0.05,5,Active
29991,140,110,0.04,7,Active
29992,4,82,0.04,3,Termed
29993,71,103,0.05,9,Active
29994,78,52,0.04,3,Active
29995,10,53,0.04,1,Active
29996,27,74,0.04,10,Active
29997,2,64,0.04,4,Termed
29998,1,99,0.05,8,Termed
29999,43,107,0.03,5,Active
30000,27,12,0.04,8,Active

In [45]:
x = df.drop("Status", axis=1)
y = df["Status"]
print(x.shape, y.shape)

(29999, 5) (29999,)

In [46]:
print (df.dtypes)

Member ID                       int64
Length                          int64
Group Size                      int64
Percentage Increase           float64
Employee Contribution Base      int64
Status                         object
dtype: object

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

x_train, x_test, y_train, y_test = train_test_split(
    x, y, random_state=1, stratify=y)
x_scaler = StandardScaler().fit(x_train)
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)